---
apiVersion: v1
kind: Pod 
metadata: 
  name: frist-pod
spec:
   containers:
     - image: nginx:1.23
       name: nginx-container
       ports:
         - containerPort: 80
           protocol: TCP
