apiVersion: v1
kind: Pod
metadata: 
  name: mysql-volume
spec:
  containers:
    - name: mysql-volume
      image: mysql:8-debian
      ports:
        - containerPort:
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employee
        - name: MYSQL_USER
          value: srinu
        - name: MYSQL_PASSWORD
          value: srinu       
      volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-volume
      emptyDir: {}           
