---
apiVersion: v1
kind: Pod 
metadata: 
  name: restart-nerver
spec:
  containers:
     - image: alpine:3
       name: restart-nerver
       command: ["sleep","2"]     
  restartPolicy: Never   
---
apiVersion: v1
kind: Pod 
metadata: 
  name: restart-nopolicy
spec:
  containers:
     - image: alpine:3
       name: restart-nopolicy
       command: 
         - sleep
         - "2"   
