---
apiVersion: v1
kind: Pod
metadata:
  name: third-pod
spec:
  containers:
    - image: alpine:3
      name: alpine-container
      command: 
        - sleep
      args: 
        - 1d
      ports:
        - containerPort: 8080
          protocol: TCP